import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "admin2@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "BMW Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 270,
      brand: "BMW",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular Shirt",
      isfeatured: true,
      banner: "/images/banner.jpg",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 280,
      brand: "BMW",
      rating: 3.2,
      numReviews: 10,
      CountInStock: 20,
      description: "A popular Shirt",
      isfeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 570,
      brand: "BMW",
      rating: 4.5,
      numReviews: 8,
      CountInStock: 20,
      description: "Another popular Shirt",
      isfeatured: true,
      banner: "/images/banner3.jpg",
    },
    {
      name: "sweat Pants",
      slug: "sweat-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 770,
      brand: "Puma",
      rating: 4.5,
      numReviews: 8,
      CountInStock: 20,
      description: "A popular pants",
      isfeatured: true,
      banner: "/images/banner4.jpg",
    },
  ],
};

export default data;
